#!/usr/bin/env bash
# Creates custom HTTP headers for two Nginx servers
FILE=/etc/nginx/sites-available/default
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "23i \\\tadd_header X-Served-By \$hostname;" $FILE
sudo service nginx restart