#!/usr/bin/env bash
# displays 'To infinity and beyond' indefinitely but 'I am invincible!!!' when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

while true;
do
	echo "To infinity and beyond"
	sleep 2
done
