#!/usr/bin/env bash
# loops from 1 to 10 and displays certain text per iteration

i=0
while (( i < 10 ))
do
	if (( i == 3 ))
	then
	   echo "bad luck"
	elif (( i == 7 ))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	(( i += 1 ))
done
