#!/usr/bin/env bash
# displays numbers from 1 to 20 and text per 4th, 9th, and 17th iteration

i=1
while (( i <= 20 ))
do
	echo "$i"
	case "$i" in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
	esac
	(( i += 1))
done
